//@version=3
strategy(title = "hktrade.github.io", shorttitle="hktrade.github.io",overlay=true)
ema1 = input(34, minval=1, maxval=300, title="EMA UpTrend")
shema = input(true, title="Show EMA Trend is Based On?")

usedEma = ema(close, ema1)

emaUpColor() => hlc3 >= usedEma
emaDownColor() => hlc3  < usedEma

col = hlc3  >= usedEma ? lime : hlc3  < usedEma ? red : white

barcolor(emaUpColor() ? lime: emaDownColor() ? red : na)
plot(shema and usedEma ? usedEma : na, title="EMA", style=line, linewidth=3, color=col)

Long_EMA = crossover(hlc3, usedEma)
Short_EMA = crossover(usedEma, hlc3)
start     = timestamp(2022, 08, 08, 00, 00)  // backtest start window
finish    = timestamp(2088, 09, 07, 11, 30)        // backtest finish window
window()  => time >= start and time <= finish ? true : false // create function "within window of time"

if window()
    strategy.entry("sell", strategy.short, 1, when=strategy.position_size <= 0 and Short_EMA)
    strategy.close("close", when=window() and Long_EMA)